### ISSUE TITLE
Error when running dw-utils clean on a folder that is not a git repo

### ISSUE THREAD

**Issue by danechitoaie** [MobiusHorizons/dw-utils#24]
If I run dw-utils clean on a folder that's not a GIT repo I get the following error.

```
Error: .git/HEAD does not exist
    at Function.configSync [as sync] (/usr/local/lib/node_modules/dw-utils/node_modules/git-branch/index.js:28:11)
    at server.auth.catch.then (/usr/local/lib/node_modules/dw-utils/clean.js:52:31)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by MobiusHorizons** [comment]
Thanks for the info, i'll look into it directly

**Comment by danechitoaie** [comment]
Looks like it's because of this https://github.com/MobiusHorizons/dw-utils/blob/master/clean.js#L55

**Comment by MobiusHorizons** [comment]
oh oops, good catch. if you have time, i'll be happy to accept a PR, otherwise i'll look into it tonight.

**Comment by danechitoaie** [comment]
#25
